[project]
name = "redskull"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.13.2",
    "asyncpg>=0.31.0",
    "discord>=2.3.2",
    "dotenv>=0.9.9",
]
